// Code generated by cmd/reset; DO NOT EDIT.

package model

func resetGenZeroValue[T any](target *T) {
	var zero T
	*target = zero
}

// Reset сбрасывает поля Metrics к начальным значениям.
func (value *Metrics) Reset() {
	if value == nil {
		return
	}
	resetGenZeroValue(&value.ID)
	resetGenZeroValue(&value.MType)
	if value.Delta != nil {
		resetGenZeroValue(value.Delta)
	}
	if value.Value != nil {
		resetGenZeroValue(value.Value)
	}
}
