package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	resetMarker       = "generate:reset"
	generatedName     = "reset.gen.go"
	defaultHelperName = "resetGenZeroValue"
)

type resetTarget struct {
	name      string
	named     *types.Named
	directory string
}

type packageTargets struct {
	pkg     *packages.Package
	targets []resetTarget
}

func main() {
	root, err := moduleRoot()
	if err != nil {
		log.Fatal(err)
	}
	if err := generate(root); err != nil {
		log.Fatal(err)
	}
}

func moduleRoot() (string, error) {
	directory, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(directory, "go.mod")); err == nil {
			return directory, nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return "", err
		}

		parent := filepath.Dir(directory)
		if parent == directory {
			return "", errors.New("go.mod not found")
		}
		directory = parent
	}
}

func generate(root string) error {
	config := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
		Dir: root,
		Env: append(os.Environ(), "GOWORK=off"),
	}

	loaded, err := packages.Load(config, "./...")
	if err != nil {
		return err
	}
	if packages.PrintErrors(loaded) > 0 {
		return errors.New("failed to load project packages")
	}

	packagesWithTargets := make([]packageTargets, 0)
	generatedTypes := make(map[string]struct{})
	for _, pkg := range loaded {
		targets := findTargets(pkg)
		if len(targets) == 0 {
			continue
		}
		sort.Slice(targets, func(i, j int) bool {
			return targets[i].name < targets[j].name
		})
		for _, target := range targets {
			generatedTypes[typeKey(target.named)] = struct{}{}
		}
		packagesWithTargets = append(packagesWithTargets, packageTargets{pkg: pkg, targets: targets})
	}

	sort.Slice(packagesWithTargets, func(i, j int) bool {
		return packagesWithTargets[i].pkg.PkgPath < packagesWithTargets[j].pkg.PkgPath
	})
	for _, current := range packagesWithTargets {
		helperName := availableHelperName(current.pkg)
		source, err := render(current.pkg.Name, helperName, current.targets, generatedTypes)
		if err != nil {
			return err
		}
		path := filepath.Join(current.targets[0].directory, generatedName)
		if err := writeGeneratedFile(path, source); err != nil {
			return err
		}
	}
	return nil
}

func findTargets(pkg *packages.Package) []resetTarget {
	var targets []resetTarget
	for _, file := range pkg.Syntax {
		filename := pkg.Fset.Position(file.Pos()).Filename
		if filepath.Base(filename) == generatedName {
			continue
		}
		for _, declaration := range file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}
			for _, specification := range general.Specs {
				typeSpec, ok := specification.(*ast.TypeSpec)
				if !ok || !hasResetMarker(typeSpec.Doc) && !hasResetMarker(general.Doc) {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.StructType); !ok {
					continue
				}
				typeName, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					continue
				}
				named, ok := typeName.Type().(*types.Named)
				if !ok {
					continue
				}
				targets = append(targets, resetTarget{
					name:      typeSpec.Name.Name,
					named:     named,
					directory: filepath.Dir(filename),
				})
			}
		}
	}
	return targets
}

func hasResetMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(comment.Text)
		text = strings.TrimSpace(strings.TrimPrefix(text, "//"))
		text = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(text, "/*"), "*/"))
		if text == resetMarker {
			return true
		}
	}
	return false
}

func availableHelperName(pkg *packages.Package) string {
	for suffix := 0; ; suffix++ {
		name := defaultHelperName
		if suffix > 0 {
			name += strconv.Itoa(suffix)
		}
		object := pkg.Types.Scope().Lookup(name)
		if object == nil || filepath.Base(pkg.Fset.Position(object.Pos()).Filename) == generatedName {
			return name
		}
	}
}

func render(packageName, helperName string, targets []resetTarget, generatedTypes map[string]struct{}) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	fmt.Fprintf(&output, "func %s[T any](target *T) {\n", helperName)
	output.WriteString("\tvar zero T\n")
	output.WriteString("\t*target = zero\n")
	output.WriteString("}\n")

	for _, target := range targets {
		structure, ok := target.named.Underlying().(*types.Struct)
		if !ok {
			continue
		}
		fmt.Fprintf(&output, "\n// Reset сбрасывает поля %s к начальным значениям.\n", target.name)
		fmt.Fprintf(&output, "func (value *%s) Reset() {\n", target.name)
		output.WriteString("\tif value == nil {\n")
		output.WriteString("\t\treturn\n")
		output.WriteString("\t}\n")
		for i := 0; i < structure.NumFields(); i++ {
			field := structure.Field(i)
			if field.Name() == "_" {
				continue
			}
			expression := "value." + field.Name()
			writeReset(&output, expression, "&"+expression, field.Type(), 1, helperName, generatedTypes)
		}
		output.WriteString("}\n")
	}

	return format.Source(output.Bytes())
}

func writeReset(output *bytes.Buffer, valueExpression, addressExpression string, fieldType types.Type, indent int, helperName string, generatedTypes map[string]struct{}) {
	prefix := strings.Repeat("\t", indent)
	underlying := types.Unalias(fieldType).Underlying()

	switch current := underlying.(type) {
	case *types.Pointer:
		if _, ok := types.Unalias(current.Elem()).Underlying().(*types.Struct); ok && isResettable(fieldType, generatedTypes) {
			fmt.Fprintf(output, "%sif %s != nil {\n", prefix, valueExpression)
			fmt.Fprintf(output, "%s\t(%s).Reset()\n", prefix, valueExpression)
			fmt.Fprintf(output, "%s}\n", prefix)
			return
		}
		fmt.Fprintf(output, "%sif %s != nil {\n", prefix, valueExpression)
		writeReset(output, "*("+valueExpression+")", valueExpression, current.Elem(), indent+1, helperName, generatedTypes)
		fmt.Fprintf(output, "%s}\n", prefix)
	case *types.Slice:
		fmt.Fprintf(output, "%s%s = (%s)[:0]\n", prefix, valueExpression, valueExpression)
	case *types.Map:
		fmt.Fprintf(output, "%sclear(%s)\n", prefix, valueExpression)
	case *types.Struct:
		if isResettable(fieldType, generatedTypes) || isResettable(types.NewPointer(fieldType), generatedTypes) {
			fmt.Fprintf(output, "%s(%s).Reset()\n", prefix, valueExpression)
			return
		}
		fmt.Fprintf(output, "%s%s(%s)\n", prefix, helperName, addressExpression)
	case *types.Interface:
		fmt.Fprintf(output, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", prefix, valueExpression)
		fmt.Fprintf(output, "%s\tresetter.Reset()\n", prefix)
		fmt.Fprintf(output, "%s} else {\n", prefix)
		fmt.Fprintf(output, "%s\t%s(%s)\n", prefix, helperName, addressExpression)
		fmt.Fprintf(output, "%s}\n", prefix)
	default:
		fmt.Fprintf(output, "%s%s(%s)\n", prefix, helperName, addressExpression)
	}
}

func isResettable(fieldType types.Type, generatedTypes map[string]struct{}) bool {
	if hasResetMethod(fieldType) {
		return true
	}
	named := namedType(fieldType)
	if named == nil {
		return false
	}
	_, ok := generatedTypes[typeKey(named)]
	return ok
}

func hasResetMethod(fieldType types.Type) bool {
	selection := types.NewMethodSet(fieldType).Lookup(nil, "Reset")
	if selection == nil {
		return false
	}
	function, ok := selection.Obj().(*types.Func)
	if !ok {
		return false
	}
	signature, ok := function.Type().(*types.Signature)
	return ok && signature.Params().Len() == 0 && signature.Results().Len() == 0
}

func namedType(fieldType types.Type) *types.Named {
	switch current := types.Unalias(fieldType).(type) {
	case *types.Named:
		return current
	case *types.Pointer:
		return namedType(current.Elem())
	default:
		return nil
	}
}

func typeKey(named *types.Named) string {
	if named == nil || named.Obj() == nil || named.Obj().Pkg() == nil {
		return ""
	}
	return named.Obj().Pkg().Path() + "." + named.Obj().Name()
}

func writeGeneratedFile(path string, source []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, source) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(path, source, 0o644)
}
